In [36]:
import pandas as pd

### Import

In [37]:
df = pd.read_csv("../data/marketing_AB.csv")
df

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14
...,...,...,...,...,...,...,...
588096,588096,1278437,ad,False,1,Tuesday,23
588097,588097,1327975,ad,False,1,Tuesday,23
588098,588098,1038442,ad,False,3,Tuesday,23
588099,588099,1496395,ad,False,1,Tuesday,23
588100,588100,1237779,ad,False,1,Tuesday,23

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Unnamed: 0     588101 non-null  int64
 1   user id        588101 non-null  int64
 2   test group     588101 non-null  str
 3   converted      588101 non-null  bool
 4   total ads      588101 non-null  int64
 5   most ads day   588101 non-null  str
 6   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(4), str(2)
memory usage: 32.6 MB

### Remove Unnecessary Index Column

I don't need the index that was a part of the inital CSV file.

In [39]:
df = df.drop(columns = ["Unnamed: 0"])
df

        user id test group  converted  total ads most ads day  most ads hour
0       1069124         ad      False        130       Monday             20
1       1119715         ad      False         93      Tuesday             22
2       1144181         ad      False         21      Tuesday             18
3       1435133         ad      False        355      Tuesday             10
4       1015700         ad      False        276       Friday             14
...         ...        ...        ...        ...          ...            ...
588096  1278437         ad      False          1      Tuesday             23
588097  1327975         ad      False          1      Tuesday             23
588098  1038442         ad      False          3      Tuesday             23
588099  1496395         ad      False          1      Tuesday             23
588100  1237779         ad      False          1      Tuesday             23

[588101 rows x 6 columns]

### Rename Columns

I prefer to use snake case for column names.

In [40]:
df.columns = df.columns.str.replace(" ", "_")
df.head()

   user_id test_group  converted  total_ads most_ads_day  most_ads_hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

### Drop Duplicate Rows

In [41]:
df.duplicated().value_counts()

False    588101
Name: count, dtype: int64

Good news, no duplicate rows.

### Handle Missing Values

In [42]:
df.isna().sum()

user_id          0
test_group       0
converted        0
total_ads        0
most_ads_day     0
most_ads_hour    0
dtype: int64

From the results it looks like we have no missing values, but there could potentially be placeholder values for nulls. With that in mind, I want to get a look at the most frequent values for each column to see if any odd outliers are present.

In [43]:
for col in df.columns:
    print(f"--- Top values in {col} ---")
    print(df[col].value_counts(dropna = False).head(5))
    print("\n")

--- Top values in user_id ---
user_id
1069124    1
1119715    1
1144181    1
1435133    1
1015700    1
Name: count, dtype: int64


--- Top values in test_group ---
test_group
ad     564577
psa     23524
Name: count, dtype: int64


--- Top values in converted ---
converted
False    573258
True      14843
Name: count, dtype: int64


--- Top values in total_ads ---
total_ads
1    56606
2    39827
5    29303
3    28661
4    23426
Name: count, dtype: int64


--- Top values in most_ads_day ---
most_ads_day
Friday      92608
Monday      87073
Sunday      85391
Thursday    82982
Saturday    81660
Name: count, dtype: int64


--- Top values in most_ads_hour ---
most_ads_hour
13    47655
12    47298
11    46210
14    45648
15    44683
Name: count, dtype: int64

I am going to expand the value counts results for the `total_ads`, `most_ads_day`, and the `most_ads_hour` columns to ensure there are no placeholder values hiding.

In [44]:
for col in ["total_ads", "most_ads_day", "most_ads_hour"]:
    print(f"--- Values in {col} ---")
    print(df[col].value_counts())
    print("\n")

--- Values in total_ads ---
total_ads
1      56606
2      39827
5      29303
3      28661
4      23426
       ...
921        1
673        1
952        1
808        1
729        1
Name: count, Length: 807, dtype: int64


--- Values in most_ads_day ---
most_ads_day
Friday       92608
Monday       87073
Sunday       85391
Thursday     82982
Saturday     81660
Wednesday    80908
Tuesday      77479
Name: count, dtype: int64


--- Values in most_ads_hour ---
most_ads_hour
13    47655
12    47298
11    46210
14    45648
15    44683
10    38939
16    37567
17    34988
18    32323
9     31004
19    30352
21    29976
20    28923
22    26432
23    20166
8     17627
7      6405
0      5536
2      5333
1      4802
3      2679
6      2068
5       765
4       722
Name: count, dtype: int64

Looks good, no null or placeholder values in the dataset.

### Time to Export

In [45]:
df.to_csv("cleaned_marketing_AB.csv", index = False)

In [46]:
pd.read_csv("cleaned_marketing_AB.csv")

        user_id test_group  converted  total_ads most_ads_day  most_ads_hour
0       1069124         ad      False        130       Monday             20
1       1119715         ad      False         93      Tuesday             22
2       1144181         ad      False         21      Tuesday             18
3       1435133         ad      False        355      Tuesday             10
4       1015700         ad      False        276       Friday             14
...         ...        ...        ...        ...          ...            ...
588096  1278437         ad      False          1      Tuesday             23
588097  1327975         ad      False          1      Tuesday             23
588098  1038442         ad      False          3      Tuesday             23
588099  1496395         ad      False          1      Tuesday             23
588100  1237779         ad      False          1      Tuesday             23

[588101 rows x 6 columns]